### ISSUE TITLE
Replace chat completion requests from OpenAI to LiteLLM

### ISSUE THREAD

**Issue by CamBish** [CamBish/indigenous-mt#14]
LiteLLM is a handy library that allows calling of many different LLMs while using OpenAI's API as a standard. Super handy!

**Comment by ishaan-jaff** [comment]
nice ! thanks for using litellm !! any feedback on how we can make it better ?

**Comment by CamBish** [comment]
so far, I have had no issues! if anything comes to mind, I will make sure to provide feedback.
